[package]
name = "tasko"
version = "0.1.0"
authors = ["Lucas Cunha <lucas.cunha@eitv.com.br>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

chrono = { version = "0.4", features = ["serde"] }
